const cropAliasMap = {
  水稻: "水稻",
  稻谷: "水稻",
  大米: "水稻",
  rice: "水稻",
  小麦: "小麦",
  麦子: "小麦",
  "winter wheat": "小麦",
  wheat: "小麦",
  玉米: "玉米",
  苞谷: "玉米",
  包谷: "玉米",
  棒子: "玉米",
  corn: "玉米",
  maize: "玉米",
  高粱: "高粱",
  蜀黍: "高粱",
  sorghum: "高粱",
  谷子: "谷子",
  小米: "谷子",
  粟: "谷子",
  millet: "谷子",
  大豆: "大豆",
  黄豆: "大豆",
  soybean: "大豆",
  soy: "大豆",
  花生: "花生",
  落花生: "花生",
  peanut: "花生",
  油菜: "油菜",
  油菜花: "油菜",
  rapeseed: "油菜",
  canola: "油菜",
  番茄: "番茄",
  西红柿: "番茄",
  tomato: "番茄",
  黄瓜: "黄瓜",
  青瓜: "黄瓜",
  cucumber: "黄瓜",
  茄子: "茄子",
  eggplant: "茄子",
  aubergine: "茄子",
  辣椒: "辣椒",
  尖椒: "辣椒",
  青椒: "辣椒",
  红椒: "辣椒",
  pepper: "辣椒",
  chili: "辣椒",
  土豆: "土豆",
  马铃薯: "土豆",
  洋芋: "土豆",
  potato: "土豆",
  红薯: "红薯",
  地瓜: "红薯",
  番薯: "红薯",
  "sweet potato": "红薯",
  白菜: "白菜",
  大白菜: "白菜",
  "chinese cabbage": "白菜",
  菠菜: "菠菜",
  spinach: "菠菜",
  洋葱: "洋葱",
  圆葱: "洋葱",
  onion: "洋葱",
  大蒜: "大蒜",
  蒜: "大蒜",
  garlic: "大蒜",
  生姜: "生姜",
  姜: "生姜",
  ginger: "生姜",
  苹果: "苹果",
  apple: "苹果",
  葡萄: "葡萄",
  grape: "葡萄",
  香蕉: "香蕉",
  banana: "香蕉",
  草莓: "草莓",
  strawberry: "草莓",
  西瓜: "西瓜",
  watermelon: "西瓜",
  柑橘: "柑橘",
  橘子: "柑橘",
  桔子: "柑橘",
  orange: "柑橘",
  梨: "梨",
  pear: "梨",
  桃子: "桃子",
  桃: "桃子",
  peach: "桃子",
  棉花: "棉花",
  cotton: "棉花",
  茶叶: "茶叶",
  茶: "茶叶",
  tea: "茶叶",
  烟草: "烟草",
  烟叶: "烟草",
  tobacco: "烟草",
  甘蔗: "甘蔗",
  sugarcane: "甘蔗",
  咖啡: "咖啡",
  coffee: "咖啡",
};

// 这个应该是要导出的函数, 用于规范化用户输入的作物名称
export const normalizeCropName = (value) => {
  const trimmedValue = value.trim();
  const lowerValue = trimmedValue.toLowerCase();

  return cropAliasMap[lowerValue] ?? trimmedValue;
};

// export const useCropNormalize = () => {
//     return {
//         cropAliasMap,
//         normalizeCropName,
//     };
// };
