packages:
  - '.'
allowBuilds:
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@langchain/core@1.2.9'
  - '@langchain/langgraph-checkpoint@1.1.5'
  - joi@18.2.5
  - langchain@1.5.10
