import { Body, Controller, Delete, Get, Param, ParseIntPipe, ParseUUIDPipe, Patch, Post, Query, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import { CurrentUser } from '../../auth/decorators/current-user.decorator';
import { UserAuthGuard } from '../../auth/guards/user-auth.guard';
import type { User } from '../../users/user.entity';
import { parse, analysisPageSchema, cropsQuerySchema, evaluationInputSchema, growthAnalysisInputSchema, knowledgeQuerySchema, landPatchSchema, landSchema, metricSchema, plantingPatchSchema, plantingSchema, plantingsQuerySchema, recordSchema, recordsQuerySchema, trendQuerySchema } from '../agriculture-v2.schemas';
import { AgricultureGrowthMetric, AgricultureGrowthMetricRecord, AgricultureLand, AgriculturePlanting } from '../entities/agriculture-v2.entity';
import { AgricultureV2AnalysisService } from '../services/agriculture-v2-analysis.service';
import { AgricultureV2Service } from '../services/agriculture-v2.service';

@ApiTags('农业')
@ApiBearerAuth()
@UseGuards(UserAuthGuard)
@Controller('api/agriculture')
export class AgricultureV2Controller {
  constructor(private readonly agriculture: AgricultureV2Service, private readonly analyses: AgricultureV2AnalysisService) {}

  @Post('lands') async createLand(@CurrentUser() user: User, @Body() body: unknown) { return this.land(await this.agriculture.createLand(user.id, parse(landSchema, body))); }
  @Get('lands') async listLands(@CurrentUser() user: User) { return (await this.agriculture.listLands(user.id)).map((land) => this.land(land)); }
  @Get('lands/:landId') async getLand(@CurrentUser() user: User, @Param('landId', ParseUUIDPipe) id: string) { return this.land(await this.agriculture.findLand(user.id, id)); }
  @Patch('lands/:landId') async patchLand(@CurrentUser() user: User, @Param('landId', ParseUUIDPipe) id: string, @Body() body: unknown) { return this.land(await this.agriculture.patchLand(user.id, id, parse(landPatchSchema, body))); }
  @Delete('lands/:landId') async deleteLand(@CurrentUser() user: User, @Param('landId', ParseUUIDPipe) id: string) { await this.agriculture.deleteLand(user.id, id); }

  @Get('crops') async listCrops(@Query() query: unknown) { const parsed = parse(cropsQuerySchema, query); const result = await this.agriculture.listCrops(parsed); return { items: result.items.map((crop) => ({ id: crop.id, standardName: crop.name, matchedName: parsed.keyword ? crop.aliases.getItems().find((alias) => alias.alias.includes(parsed.keyword!))?.alias ?? crop.name : crop.name })), pagination: this.pagination(result) }; }
  @Get('crops/:cropId') async getCrop(@Param('cropId', ParseIntPipe) id: number) { const crop = await this.agriculture.findCrop(id); return { id: crop.id, standardName: crop.name, aliases: crop.aliases.getItems().map((alias) => alias.alias), introduction: crop.introduction, suitableEnvironment: crop.suitableEnvironment, growthStages: crop.growthStages ?? [], managementNotes: crop.managementNotes, commonPests: crop.commonPests ?? [] }; }
  @Get('knowledge') async listKnowledge(@Query() query: unknown) { const result = await this.agriculture.listKnowledge(parse(knowledgeQuerySchema, query)); return { items: result.items.map((item) => ({ id: item.id, title: item.title, category: item.category, source: { name: item.sourceName } })), pagination: this.pagination(result) }; }
  @Get('knowledge/:knowledgeId') async getKnowledge(@Param('knowledgeId', ParseIntPipe) id: number) { const item = await this.agriculture.findKnowledge(id); return { id: item.id, title: item.title, category: item.category, content: item.content, source: { name: item.sourceName, title: item.sourceTitle, url: item.sourceUrl }, relatedCrops: item.crops.getItems().map((crop) => ({ id: crop.id, name: crop.name })) }; }

  @Post('lands/:landId/planting-evaluations') async evaluate(@CurrentUser() user: User, @Param('landId', ParseUUIDPipe) id: string, @Body() body: unknown) { return this.evaluation(await this.analyses.evaluatePlanting(user.id, id, parse(evaluationInputSchema, body))); }
  @Get('lands/:landId/planting-evaluations') async listEvaluations(@CurrentUser() user: User, @Param('landId', ParseUUIDPipe) id: string, @Query() query: unknown) { const page = parse(analysisPageSchema, query); const result = await this.agriculture.listEvaluations(user.id, id, page.page, page.pageSize); return { items: result.items.map((item) => ({ id: item.id, crop: { name: item.cropName }, summary: item.summary, suitability: item.suitability, createdAt: item.createdAt.toISOString() })), pagination: this.pagination(result) }; }
  @Get('planting-evaluations/:evaluationId') async getEvaluation(@CurrentUser() user: User, @Param('evaluationId', ParseUUIDPipe) id: string) { return this.evaluation(await this.agriculture.findEvaluation(user.id, id)); }

  @Post('lands/:landId/plantings') async createPlanting(@CurrentUser() user: User, @Param('landId', ParseUUIDPipe) id: string, @Body() body: unknown) { return this.planting(await this.agriculture.createPlanting(user.id, id, parse(plantingSchema, body))); }
  @Get('plantings') async listPlantings(@CurrentUser() user: User, @Query() query: unknown) { const result = await this.agriculture.listPlantings(user.id, parse(plantingsQuerySchema, query)); return { items: result.items.map((item) => this.planting(item)), pagination: this.pagination(result) }; }
  @Get('plantings/:plantingId') async getPlanting(@CurrentUser() user: User, @Param('plantingId', ParseUUIDPipe) id: string) { return this.planting(await this.agriculture.findPlanting(user.id, id)); }
  @Patch('plantings/:plantingId') async patchPlanting(@CurrentUser() user: User, @Param('plantingId', ParseUUIDPipe) id: string, @Body() body: unknown) { return this.planting(await this.agriculture.patchPlanting(user.id, id, parse(plantingPatchSchema, body))); }
  @Delete('plantings/:plantingId') async deletePlanting(@CurrentUser() user: User, @Param('plantingId', ParseUUIDPipe) id: string) { await this.agriculture.deletePlanting(user.id, id); }

  @Post('plantings/:plantingId/metrics') async createMetric(@CurrentUser() user: User, @Param('plantingId', ParseUUIDPipe) id: string, @Body() body: unknown) { return this.metric(await this.agriculture.createMetric(user.id, id, parse(metricSchema, body))); }
  @Get('plantings/:plantingId/metrics') async listMetrics(@CurrentUser() user: User, @Param('plantingId', ParseUUIDPipe) id: string) { return (await this.agriculture.listMetrics(user.id, id)).map((metric) => this.metric(metric)); }
  @Delete('metrics/:metricId') async deleteMetric(@CurrentUser() user: User, @Param('metricId', ParseUUIDPipe) id: string) { await this.agriculture.deleteMetric(user.id, id); }
  @Post('metrics/:metricId/records') async createRecord(@CurrentUser() user: User, @Param('metricId', ParseUUIDPipe) id: string, @Body() body: unknown) { return this.record(await this.agriculture.createRecord(user.id, id, parse(recordSchema, body))); }
  @Get('metrics/:metricId/records') async listRecords(@CurrentUser() user: User, @Param('metricId', ParseUUIDPipe) id: string, @Query() query: unknown) { const result = await this.agriculture.listRecords(user.id, id, parse(recordsQuerySchema, query)); return { items: result.items.map((record) => this.record(record)), pagination: this.pagination(result) }; }
  @Delete('metrics/:metricId/records/:recordId') async deleteRecord(@CurrentUser() user: User, @Param('metricId', ParseUUIDPipe) metricId: string, @Param('recordId', ParseUUIDPipe) recordId: string) { await this.agriculture.deleteRecord(user.id, metricId, recordId); }
  @Get('metrics/:metricId/trend') async trend(@CurrentUser() user: User, @Param('metricId', ParseUUIDPipe) id: string, @Query() query: unknown) { const result = await this.agriculture.trend(user.id, id, parse(trendQuerySchema, query)); return { metric: { id: result.metric.id, name: result.metric.name, unit: result.metric.unit }, latestValue: result.latestValue, trend: result.trend, change: result.change, averageChange: result.averageChange, points: result.points.map((point) => ({ value: point.value, recordedAt: point.recordedAt.toISOString() })) }; }

  @Post('plantings/:plantingId/growth-analyses') async analyzeGrowth(@CurrentUser() user: User, @Param('plantingId', ParseUUIDPipe) id: string, @Body() body: unknown) { return this.growthAnalysis(await this.analyses.analyzeGrowth(user.id, id, parse(growthAnalysisInputSchema, body))); }
  @Get('plantings/:plantingId/growth-analyses') async listGrowthAnalyses(@CurrentUser() user: User, @Param('plantingId', ParseUUIDPipe) id: string, @Query() query: unknown) { const page = parse(analysisPageSchema, query); const result = await this.agriculture.listAnalyses(user.id, id, page.page, page.pageSize); return { items: result.items.map((item) => ({ id: item.id, summary: item.summary, growthStatus: item.growthStatus, createdAt: item.createdAt.toISOString() })), pagination: this.pagination(result) }; }
  @Get('growth-analyses/:analysisId') async getGrowthAnalysis(@CurrentUser() user: User, @Param('analysisId', ParseUUIDPipe) id: string) { return this.growthAnalysis(await this.agriculture.findAnalysis(user.id, id)); }

  private land(item: AgricultureLand) { return { id: item.id, name: item.name, region: { province: item.province, city: item.city, district: item.district }, plantingEnvironment: item.plantingEnvironment, area: item.areaValue === null || item.areaUnit === null ? null : { value: Number(item.areaValue), unit: item.areaUnit }, soil: item.soil, irrigation: item.irrigation, drainage: item.drainage, description: item.description, createdAt: item.createdAt.toISOString(), updatedAt: item.updatedAt.toISOString() }; }
  private planting(item: AgriculturePlanting) { return { id: item.id, landId: item.land.id, crop: { id: item.crop.id, standardName: item.crop.name }, variety: item.variety, plantingTime: item.plantingDate ? { type: 'date', date: item.plantingDate } : item.plantingTimeText ? { type: 'text', text: item.plantingTimeText } : null, growthStage: item.growthStage, status: item.status, description: item.description, createdAt: item.createdAt.toISOString(), updatedAt: item.updatedAt.toISOString() }; }
  private metric(item: AgricultureGrowthMetric) { const records = item.records.isInitialized() ? item.records.getItems() : []; const latest = [...records].sort((a, b) => b.recordedAt.getTime() - a.recordedAt.getTime())[0]; return { id: item.id, name: item.name, unit: item.unit, latestValue: latest ? Number(latest.value) : null, latestRecordedAt: latest?.recordedAt.toISOString() ?? null, recordCount: records.length }; }
  private record(item: AgricultureGrowthMetricRecord) { return { id: item.id, value: Number(item.value), recordedAt: item.recordedAt.toISOString(), note: item.note, createdAt: item.createdAt.toISOString() }; }
  private evaluation(item: { id: string; inputSnapshot: Record<string, unknown>; resultSnapshot: Record<string, unknown>; createdAt: Date }) { const context = { ...item.inputSnapshot }; delete context.knowledgeContext; return { id: item.id, context, result: item.resultSnapshot, createdAt: item.createdAt.toISOString() }; }
  private growthAnalysis(item: { id: string; inputSnapshot: Record<string, unknown>; resultSnapshot: Record<string, unknown>; createdAt: Date }) { const context = { ...item.inputSnapshot }; delete context.knowledgeContext; const weather = context.weather as { availability?: string; warning?: string } | undefined; return { id: item.id, context, result: item.resultSnapshot, warnings: weather?.availability === 'unavailable' && weather.warning ? [weather.warning] : [], createdAt: item.createdAt.toISOString() }; }
  private pagination(result: { page: number; pageSize: number; total: number }) { return { page: result.page, pageSize: result.pageSize, total: result.total }; }
}
