<script setup lang="ts">
import type { HealthAnalysisResult } from '../types/health'
const props = defineProps<{ result: HealthAnalysisResult | null }>()
const emit = defineEmits<{ knowledge: [id: number] }>()
</script>

<template><section class="health-card" aria-labelledby="analysis-result-title"><div class="section-heading"><div><p class="eyebrow">分析结果</p><h2 id="analysis-result-title">本次健康信息</h2></div></div><van-empty v-if="!props.result" image="search" description="完成一次分析后在这里查看结果" /><template v-else><p class="notice">以下内容基于你提供的信息和当前账号已有健康上下文，仅供日常观察和生活方式参考，不构成疾病诊断或处方建议。</p><p class="summary">{{ props.result.summary }}</p><div class="result-block"><h3>需要关注</h3><ul><li v-for="item in props.result.concerns" :key="item">{{ item }}</li><li v-if="!props.result.concerns.length">暂无额外关注事项</li></ul></div><div class="result-block"><h3>可能影响因素</h3><ul><li v-for="item in props.result.factors" :key="item">{{ item }}</li><li v-if="!props.result.factors.length">暂无相关因素</li></ul></div><div class="result-block"><h3>日常建议</h3><ul><li v-for="item in props.result.suggestions" :key="item">{{ item }}</li></ul></div><div class="advice"><h3>就医提示</h3><p>{{ props.result.medicalAdvice }}</p></div><div v-if="props.result.references.length" class="result-block"><h3>参考知识</h3><button v-for="reference in props.result.references" :key="reference.knowledgeId" type="button" class="reference" @click="emit('knowledge', reference.knowledgeId)">{{ reference.title }} · {{ reference.source }}</button></div></template></section></template>

<style scoped>
.health-card { padding: 20px 16px; background: var(--color-bg-primary); border-radius: 16px; }.section-heading { margin-bottom: 12px; }.eyebrow { margin: 0 0 4px; color: var(--color-health); font-size: 14px; font-weight: 600; }.section-heading h2 { margin: 0; color: var(--color-text-primary); font-size: 20px; }.notice { margin: 0 0 12px; padding: 10px 12px; border-radius: 10px; background: var(--color-health-soft); color: var(--color-health); font-size: 14px; line-height: 1.6; }.summary { color: var(--color-text-primary); font-size: 16px; line-height: 1.7; }.result-block { margin-top: 18px; }.result-block h3, .advice h3 { margin: 0 0 8px; color: var(--color-text-primary); font-size: 16px; }.result-block ul { margin: 0; padding-left: 20px; color: var(--color-text-secondary); line-height: 1.7; }.advice { margin-top: 18px; padding: 12px; border-radius: 10px; background: rgb(237 111 33 / 10%); }.advice p { margin: 0; color: var(--color-text-secondary); line-height: 1.6; }.reference { display: block; width: 100%; margin-top: 8px; padding: 10px 0; border: 0; border-bottom: 1px solid var(--color-divider); background: transparent; color: var(--color-primary); text-align: left; font: inherit; }
</style>
