<script setup lang="ts">
import { computed, reactive } from 'vue'
import HealthSafetyResult from './HealthSafetyResult.vue'
import type { CreateAssessmentInput, HealthAssessment, HealthMeasurement } from '../types/health'
const props = defineProps<{ items: HealthAssessment[]; measurements: HealthMeasurement[]; loading: boolean; saving: boolean; enabled: boolean }>()
const emit = defineEmits<{ create: [input: CreateAssessmentInput]; remove: [id: string] }>()
const form = reactive({ code: 'fever', severity: 'moderate' as 'mild' | 'moderate' | 'severe', course: 'new' as 'new' | 'intermittent' | 'persistent', startedAt: new Date().toISOString().slice(0, 16), otherDetails: '', measurementIds: [] as string[] })
const latest = computed(() => props.items[0] ?? null)
function submit(): void { if (!form.code || !form.startedAt) return; emit('create', { idempotencyKey: crypto.randomUUID(), symptoms: [{ code: form.code, severity: form.severity, course: form.course, startedAt: new Date(form.startedAt).toISOString() }], otherDetails: form.otherDetails.trim() || undefined, measurementIds: form.measurementIds }) }
</script>
<template><section class="panel"><h2>健康评估</h2><p class="hint">健康评估仅提供就医引导和健康信息，不构成诊断或处方。</p><p v-if="!enabled" class="hint">请先授权“健康评估”后再提交。</p><template v-else><van-cell-group inset><van-field v-model="form.code" label="当前不适"><template #input><select v-model="form.code"><option value="fever">发热</option><option value="cough">咳嗽</option><option value="fatigue">乏力</option><option value="dizziness">头晕</option><option value="headache">头痛</option><option value="chest_discomfort">胸部不适</option><option value="difficulty_breathing">呼吸困难</option><option value="other">其他</option></select></template></van-field><van-field v-model="form.severity" label="感受程度"><template #input><select v-model="form.severity"><option value="mild">轻微</option><option value="moderate">中等</option><option value="severe">严重</option></select></template></van-field><van-field v-model="form.course" label="持续情况"><template #input><select v-model="form.course"><option value="new">新出现</option><option value="intermittent">间歇出现</option><option value="persistent">持续存在</option></select></template></van-field><van-field v-model="form.startedAt" type="datetime-local" label="开始时间" /><van-field v-model="form.otherDetails" type="textarea" rows="2" maxlength="1000" label="补充说明" /></van-cell-group><van-checkbox-group v-model="form.measurementIds" class="measurements"><van-checkbox v-for="measurement in measurements" :key="measurement.id" :name="measurement.id">关联 {{ measurement.type }}（{{ new Date(measurement.measuredAt).toLocaleDateString() }}）</van-checkbox></van-checkbox-group><van-button block round type="primary" :loading="saving" @click="submit">提交健康评估</van-button></template><HealthSafetyResult v-if="latest" :assessment="latest" /><van-loading v-if="loading">正在加载…</van-loading><van-empty v-else-if="!items.length" description="暂无健康评估记录" /><van-cell-group v-else inset><van-cell v-for="item in items" :key="item.id" :title="item.triage.message" :label="new Date(item.createdAt).toLocaleString()"><template #right-icon><van-button size="small" plain type="danger" @click="emit('remove', item.id)">删除</van-button></template></van-cell></van-cell-group></section></template>
<style scoped>.panel { display: grid; gap: 12px; padding: 16px; }.panel h2 { margin: 0; font-size: 20px; }.hint { margin: 0; color: var(--color-text-secondary); font-size: 14px; line-height: 1.6; }.measurements { display: grid; gap: 10px; padding: 0 16px; }</style>
