<script setup lang="ts">
import { reactive } from 'vue'
import type { KnowledgeFilters, KnowledgeSummary } from '../types/health'

const props = defineProps<{ items: KnowledgeSummary[]; loading: boolean; errorMessage: string; total: number; page: number; pageSize: number; filters: KnowledgeFilters }>()
const emit = defineEmits<{ search: [filters: { q: string; category: string }]; select: [id: number]; pageChange: [page: number] }>()
const draft = reactive({ q: props.filters.q ?? '', category: props.filters.category ?? '' })

function search(): void { emit('search', { q: draft.q.trim(), category: draft.category }) }
</script>

<template><section class="health-card" aria-labelledby="knowledge-title"><div class="section-heading"><div><p class="eyebrow">健康知识</p><h2 id="knowledge-title">浏览可信的健康内容</h2></div></div><form class="search-form" @submit.prevent="search"><input v-model="draft.q" aria-label="搜索健康知识" placeholder="搜索血压、睡眠等" /><select v-model="draft.category" aria-label="知识分类"><option value="">全部分类</option><option value="health_metric">健康指标</option><option value="lifestyle">生活方式</option></select><van-button type="primary" native-type="submit">搜索</van-button></form><p v-if="errorMessage" class="error" role="alert">{{ errorMessage }}</p><van-loading v-if="loading" class="inline-loading">正在加载知识…</van-loading><van-empty v-else-if="!props.items.length" image="search" description="暂无匹配的健康知识" /><div v-else class="knowledge-list"><button v-for="item in props.items" :key="item.id" type="button" class="knowledge-item" @click="emit('select', item.id)"><span><strong>{{ item.title }}</strong><small>{{ item.summary || '查看知识详情和来源' }}</small><small>{{ item.sourceName || '来源信息见详情' }} · {{ item.tags.join('、') }}</small></span><span aria-hidden="true">›</span></button></div><div v-if="total > pageSize" class="pager"><van-button size="small" plain :disabled="page <= 1" @click="emit('pageChange', page - 1)">上一页</van-button><span>第 {{ page }} 页</span><van-button size="small" plain :disabled="page * pageSize >= total" @click="emit('pageChange', page + 1)">下一页</van-button></div></section></template>

<style scoped>
.health-card { padding: 20px 16px; background: var(--color-bg-primary); border-radius: 16px; }.section-heading { margin-bottom: 14px; }.eyebrow { margin: 0 0 4px; color: var(--color-health); font-size: 14px; font-weight: 600; }.section-heading h2 { margin: 0; color: var(--color-text-primary); font-size: 20px; }.search-form { display: grid; grid-template-columns: minmax(0, 1fr) 120px auto; gap: 8px; }.search-form input, .search-form select { box-sizing: border-box; width: 100%; min-width: 0; padding: 10px 11px; border: 1px solid var(--color-divider); border-radius: 10px; background: var(--color-bg-primary); color: var(--color-text-primary); font: inherit; }.error { margin: 12px 0 0; color: var(--color-danger); }.inline-loading { padding: 24px 0; text-align: center; }.knowledge-list { margin-top: 12px; }.knowledge-item { display: flex; align-items: center; justify-content: space-between; width: 100%; gap: 12px; padding: 14px 0; border: 0; border-top: 1px solid var(--color-divider); background: transparent; color: var(--color-text-primary); text-align: left; font: inherit; }.knowledge-item strong, .knowledge-item small { display: block; }.knowledge-item small { margin-top: 5px; color: var(--color-text-secondary); font-size: 13px; line-height: 1.5; }.knowledge-item > span:last-child { color: var(--color-primary); font-size: 24px; }.pager { display: flex; align-items: center; justify-content: center; gap: 12px; padding-top: 12px; color: var(--color-text-secondary); font-size: 13px; }@media (max-width: 520px) { .search-form { grid-template-columns: 1fr 1fr; }.search-form input { grid-column: 1 / -1; }.search-form .van-button { grid-column: 1 / -1; } }
</style>
