<script setup lang="ts">
import { computed, reactive } from 'vue'
import type { CreateMeasurementInput, HealthMeasurement, MeasurementType } from '../types/health'
defineProps<{ items: HealthMeasurement[]; loading: boolean; saving: boolean; enabled: boolean }>()
const emit = defineEmits<{ create: [input: CreateMeasurementInput]; remove: [id: string] }>()
const form = reactive({ type: 'body_temperature' as MeasurementType, source: 'self_reported' as CreateMeasurementInput['source'], value: '', secondaryValue: '', measuredAt: new Date().toISOString().slice(0, 16) })
const unit = computed(() => ({ blood_pressure: 'mmHg', body_temperature: 'celsius', heart_rate: 'bpm', body_weight: 'kg', body_height: 'cm' })[form.type])
function submit(): void { const value = Number(form.value); const secondary = Number(form.secondaryValue); if (!Number.isFinite(value) || (form.type === 'blood_pressure' && !Number.isFinite(secondary))) return; const values: Record<string, string | number> = form.type === 'blood_pressure' ? { systolic: value, diastolic: secondary, unit: 'mmHg' } : { value, unit: unit.value }; emit('create', { type: form.type, source: form.source, measuredAt: new Date(form.measuredAt).toISOString(), values }) }
function text(item: HealthMeasurement): string { const values = item.values; return item.type === 'blood_pressure' ? `${values.systolic}/${values.diastolic} ${values.unit}` : `${values.value} ${values.unit}` }
</script>
<template><section class="panel"><h2>健康测量</h2><p v-if="!enabled" class="hint">请先授权“健康测量”后再记录。</p><template v-else><van-cell-group inset><van-field v-model="form.type" label="类型"><template #input><select v-model="form.type"><option value="body_temperature">体温</option><option value="heart_rate">心率</option><option value="body_weight">体重</option><option value="body_height">身高</option><option value="blood_pressure">血压</option></select></template></van-field><van-field v-model="form.value" type="number" :label="form.type === 'blood_pressure' ? '收缩压' : '数值'" :placeholder="unit" /><van-field v-if="form.type === 'blood_pressure'" v-model="form.secondaryValue" type="number" label="舒张压" placeholder="mmHg" /><van-field v-model="form.measuredAt" type="datetime-local" label="测量时间" /></van-cell-group><van-button block round type="primary" :loading="saving" @click="submit">保存测量</van-button><van-loading v-if="loading">正在加载…</van-loading><van-empty v-else-if="!items.length" description="还没有健康测量记录" /><van-cell-group v-else inset><van-cell v-for="item in items" :key="item.id" :title="text(item)" :label="new Date(item.measuredAt).toLocaleString()"><template #right-icon><van-button size="small" plain type="danger" @click="emit('remove', item.id)">删除</van-button></template></van-cell></van-cell-group></template></section></template>
<style scoped>.panel { display: grid; gap: 12px; padding: 16px; }.panel h2 { margin: 0; font-size: 20px; }.hint { margin: 0; color: var(--color-text-secondary); }</style>
