<template>
  <main class="healthy-page"><FunctionHeader title="健康评估与健康知识" />
    <section class="card"><h1>健康信息记录与就医引导</h1><p>本服务不提供诊断、疾病概率或用药方案。</p></section>
    <section class="card"><h2>单独同意</h2><p>用于保存本人健康记录和生成受限的 AI 健康说明，可随时撤回。</p><van-button v-if="!consented" type="primary" @click="grant">同意并继续</van-button><van-button v-else plain type="danger" @click="revoke">撤回同意</van-button></section>
    <section class="card"><h2>当前不适</h2><van-field v-model="details" type="textarea" maxlength="500" show-word-limit placeholder="请描述当前不适、开始时间和持续情况"/><van-button block type="primary" :loading="loading" :disabled="!consented" @click="assess">获取健康说明</van-button></section>
    <section v-if="unavailable" class="card unavailable"><h2>暂时无法评估</h2><p>当前信息不足或服务暂不可用。若症状明显、持续或加重，请及时寻求专业帮助。</p></section>
    <section v-if="result" class="card" :class="{ emergency: result.triage.level === 'emergency' }"><div v-if="result.triage.level === 'emergency'" class="emergency-action"><strong>请立即求助：拨打 120 或前往急诊</strong></div><h2>就医紧迫度：{{ triageLabel }}</h2><p>{{ result.triage.message }}</p><h3>下一步行动</h3><ul><li v-for="item in result.nextActions" :key="item">{{ item }}</li></ul><h3 v-if="result.warningSignals.length">警惕信号</h3><ul v-if="result.warningSignals.length"><li v-for="item in result.warningSignals" :key="item">{{ item }}</li></ul><h3>知识来源</h3><ul><li v-for="item in result.knowledgeReferences" :key="`${item.knowledgeId}-${item.version}`">{{ item.title }}（{{ item.sourceName }}）</li></ul><p class="notice">AI 生成说明，仅供健康信息参考，不构成诊断。</p><p v-for="item in result.limitations" :key="item" class="notice">{{ item }}</p></section>
  </main>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from "vue"; import { showNotify } from "vant"; import FunctionHeader from "@/components/layout/FunctionHeader.vue"; import { createHealthAssessment, getCurrentHealthConsent, grantHealthConsent, revokeHealthConsent } from "@/api/modules/healthy"; import { isHealthAssessmentResult, type HealthAssessmentResult } from "@/modules/healthy/types";
const consented = ref(false); const loading = ref(false); const unavailable = ref(false); const details = ref(""); const result = ref<HealthAssessmentResult | null>(null);
const triageLabel = computed(() => ({ emergency: "立即求助", urgent: "尽快就医", routine: "安排就医", self_care: "自我照护", insufficient: "信息不足" }[result.value?.triage.level ?? "insufficient"]));
onMounted(async () => { try { consented.value = Boolean((await getCurrentHealthConsent()).data); } catch { unavailable.value = true; } });
const grant = async () => { await grantHealthConsent({ noticeVersion: "1.0", scopes: ["profile", "measurement", "assessment", "ai_processing"] }); consented.value = true; };
const revoke = async () => { await revokeHealthConsent(); consented.value = false; result.value = null; };
const assess = async () => { loading.value = true; unavailable.value = false; result.value = null; try { const response = await createHealthAssessment({ idempotencyKey: crypto.randomUUID(), symptoms: details.value.trim() ? [{ code: "other", severity: "moderate", startedAt: new Date().toISOString(), course: "new" }] : [], otherDetails: details.value.trim() || undefined }); if (!isHealthAssessmentResult(response.data)) throw new Error("invalid response"); result.value = response.data; } catch { unavailable.value = true; showNotify({ type: "warning", message: "暂时无法评估", position: "top" }); } finally { loading.value = false; } };
</script>
<style scoped lang="scss">.healthy-page{min-height:100dvh;padding:12px;background:#f4fbfa;color:#173f42}.card{margin:12px 0;padding:18px;border-radius:16px;background:#fff;box-shadow:0 4px 16px #1b66521a}h1,h2,h3{font-weight:800}.card p,li{font-size:16px;line-height:1.6}.card .van-button{margin-top:12px}.emergency,.unavailable{border:2px solid #d94b42}.emergency-action{padding:12px;background:#fff0ef;color:#b42318;font-size:18px}.notice{color:#607d80;font-size:14px}</style>
