import { Migration } from '@mikro-orm/migrations';

export class Migration20260919090000_add_agriculture_v2 extends Migration {
  override name = 'Migration20260919090000_add_agriculture_v2';

  override up(): void {
    this.addSql(`alter table "agriculture_crops" add column "introduction" text null, add column "suitable_environment" text null, add column "growth_stages" jsonb null, add column "management_notes" text null, add column "common_pests" jsonb null;`);
    this.addSql(`alter table "agriculture_knowledge" add column "source_title" varchar(255) null, add column "region_tags" text[] not null default '{}';`);
    this.addSql(`create table "agriculture_lands" ("id" uuid not null, "user_id" int not null, "name" varchar(100) not null, "province" varchar(50) not null, "city" varchar(50) not null, "district" varchar(50) not null, "planting_environment" varchar(32) not null, "area_value" numeric(12,2) null, "area_unit" varchar(16) null, "soil" varchar(100) null, "irrigation" varchar(32) null, "drainage" varchar(32) null, "description" text null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), constraint "agriculture_lands_pkey" primary key ("id"), constraint "agriculture_lands_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete restrict); create index "agriculture_lands_user_id_index" on "agriculture_lands" ("user_id"); create index "agriculture_lands_user_id_created_at_index" on "agriculture_lands" ("user_id", "created_at" desc);`);
    this.addSql(`create table "agriculture_plantings" ("id" uuid not null, "land_id" uuid not null, "crop_id" int not null, "variety" varchar(100) null, "planting_date" date null, "planting_time_text" varchar(100) null, "growth_stage" varchar(100) null, "status" varchar(32) not null default 'planned', "description" text null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), constraint "agriculture_plantings_pkey" primary key ("id"), constraint "agriculture_plantings_time_check" check (not ("planting_date" is not null and "planting_time_text" is not null)), constraint "agriculture_plantings_land_id_foreign" foreign key ("land_id") references "agriculture_lands" ("id") on delete restrict, constraint "agriculture_plantings_crop_id_foreign" foreign key ("crop_id") references "agriculture_crops" ("id") on delete restrict); create index "agriculture_plantings_land_id_index" on "agriculture_plantings" ("land_id"); create index "agriculture_plantings_crop_id_index" on "agriculture_plantings" ("crop_id"); create index "agriculture_plantings_land_id_status_index" on "agriculture_plantings" ("land_id", "status");`);
    this.addSql(`create table "agriculture_growth_metrics" ("id" uuid not null, "planting_id" uuid not null, "name" varchar(100) not null, "unit" varchar(32) not null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), constraint "agriculture_growth_metrics_pkey" primary key ("id"), constraint "agriculture_growth_metrics_planting_id_name_unique" unique ("planting_id", "name"), constraint "agriculture_growth_metrics_planting_id_foreign" foreign key ("planting_id") references "agriculture_plantings" ("id") on delete restrict); create index "agriculture_growth_metrics_planting_id_index" on "agriculture_growth_metrics" ("planting_id");`);
    this.addSql(`create table "agriculture_growth_metric_records" ("id" uuid not null, "metric_id" uuid not null, "value" numeric(14,4) not null, "recorded_at" timestamptz not null, "note" text null, "created_at" timestamptz not null default now(), constraint "agriculture_growth_metric_records_pkey" primary key ("id"), constraint "agriculture_growth_metric_records_metric_id_foreign" foreign key ("metric_id") references "agriculture_growth_metrics" ("id") on delete restrict); create index "agriculture_growth_metric_records_metric_id_recorded_at_index" on "agriculture_growth_metric_records" ("metric_id", "recorded_at");`);
    this.addSql(`create table "agriculture_planting_evaluations" ("id" uuid not null, "land_id" uuid not null, "crop_id" int null, "crop_name" varchar(100) not null, "variety" varchar(100) null, "planned_planting_time" varchar(100) null, "summary" text not null, "suitability" varchar(32) not null, "schema_version" smallint not null default 1, "input_snapshot" jsonb not null, "result_snapshot" jsonb not null, "created_at" timestamptz not null default now(), constraint "agriculture_planting_evaluations_pkey" primary key ("id"), constraint "agriculture_planting_evaluations_land_id_foreign" foreign key ("land_id") references "agriculture_lands" ("id") on delete restrict, constraint "agriculture_planting_evaluations_crop_id_foreign" foreign key ("crop_id") references "agriculture_crops" ("id") on delete restrict); create index "agriculture_planting_evaluations_land_id_created_at_index" on "agriculture_planting_evaluations" ("land_id", "created_at" desc); create index "agriculture_planting_evaluations_crop_id_index" on "agriculture_planting_evaluations" ("crop_id"); create index "agriculture_planting_evaluations_suitability_index" on "agriculture_planting_evaluations" ("suitability");`);
    this.addSql(`create table "agriculture_growth_analyses" ("id" uuid not null, "planting_id" uuid not null, "summary" text not null, "growth_status" varchar(32) not null, "schema_version" smallint not null default 1, "input_snapshot" jsonb not null, "result_snapshot" jsonb not null, "created_at" timestamptz not null default now(), constraint "agriculture_growth_analyses_pkey" primary key ("id"), constraint "agriculture_growth_analyses_planting_id_foreign" foreign key ("planting_id") references "agriculture_plantings" ("id") on delete restrict); create index "agriculture_growth_analyses_planting_id_created_at_index" on "agriculture_growth_analyses" ("planting_id", "created_at" desc); create index "agriculture_growth_analyses_growth_status_index" on "agriculture_growth_analyses" ("growth_status");`);
  }

  override down(): void {
    this.addSql(`drop table if exists "agriculture_growth_analyses"; drop table if exists "agriculture_planting_evaluations"; drop table if exists "agriculture_growth_metric_records"; drop table if exists "agriculture_growth_metrics"; drop table if exists "agriculture_plantings"; drop table if exists "agriculture_lands"; alter table "agriculture_knowledge" drop column if exists "region_tags", drop column if exists "source_title"; alter table "agriculture_crops" drop column if exists "common_pests", drop column if exists "management_notes", drop column if exists "growth_stages", drop column if exists "suitable_environment", drop column if exists "introduction";`);
  }
}
