import { Migration } from '@mikro-orm/migrations';

/**
 * Keeps the removed M09 runtime schema intact under explicit legacy names,
 * then creates the V2 health schema defined in docs/module/health/database.md.
 */
export class Migration20260917120000_replace_legacy_health extends Migration {
  override name = 'Migration20260917120000_replace_legacy_health';

  override up(): void {
    this.addSql('alter table "health_consents" rename to "legacy_health_consents";');
    this.addSql('alter table "health_profiles" rename to "legacy_health_profiles";');
    this.addSql('alter table "health_measurements" rename to "legacy_health_measurements";');
    this.addSql('alter table "health_knowledge_articles" rename to "legacy_health_knowledge_articles";');
    this.addSql('alter table "health_knowledge_versions" rename to "legacy_health_knowledge_versions";');
    this.addSql('alter table "health_assessments" rename to "legacy_health_assessments";');
    this.addSql('alter table "health_access_audits" rename to "legacy_health_access_audits";');

    this.addSql(`create table "health_profiles" (
      "id" integer generated by default as identity primary key,
      "user_id" integer not null unique,
      "sex" varchar(20) null,
      "birth_date" date null,
      "height_cm" numeric(5,2) null,
      "smoking_status" varchar(20) null,
      "drinking_status" varchar(20) null,
      "exercise_status" varchar(20) null,
      "sleep_status" varchar(20) null,
      "health_history" text null,
      "allergies" text null,
      "created_at" timestamptz not null,
      "updated_at" timestamptz not null,
      constraint "health_profiles_user_id_foreign" foreign key ("user_id") references "users" ("id")
    );`);

    this.addSql(`create table "health_metric_templates" (
      "id" integer generated by default as identity primary key,
      "user_id" integer not null,
      "name" varchar(100) not null,
      "metric_name" varchar(100) not null,
      "unit" varchar(30) not null,
      "related_system_metric_type" varchar(30) null,
      "started_at" timestamptz not null,
      "ended_at" timestamptz null,
      "created_at" timestamptz not null,
      "updated_at" timestamptz not null,
      constraint "health_metric_templates_user_id_foreign" foreign key ("user_id") references "users" ("id"),
      constraint "health_metric_templates_related_type_check" check ("related_system_metric_type" in ('weight', 'blood_pressure', 'heart_rate', 'temperature') or "related_system_metric_type" is null),
      constraint "health_metric_templates_period_check" check ("ended_at" is null or "ended_at" >= "started_at")
    );`);
    this.addSql('create index "idx_health_metric_templates_user_id" on "health_metric_templates" ("user_id");');
    this.addSql('create index "idx_health_metric_templates_user_id_ended_at" on "health_metric_templates" ("user_id", "ended_at");');

    this.addSql(`create table "health_metric_records" (
      "id" integer generated by default as identity primary key,
      "user_id" integer not null,
      "metric_type" varchar(30) not null,
      "template_id" integer null,
      "numeric_value" numeric null,
      "systolic_value" numeric null,
      "diastolic_value" numeric null,
      "unit" varchar(30) not null,
      "measured_at" timestamptz not null,
      "created_at" timestamptz not null,
      constraint "health_metric_records_user_id_foreign" foreign key ("user_id") references "users" ("id"),
      constraint "health_metric_records_template_id_foreign" foreign key ("template_id") references "health_metric_templates" ("id") on delete restrict,
      constraint "health_metric_records_type_check" check ("metric_type" in ('weight', 'blood_pressure', 'heart_rate', 'temperature', 'custom')),
      constraint "health_metric_records_value_shape_check" check (("metric_type" = 'blood_pressure' and "numeric_value" is null and "systolic_value" is not null and "diastolic_value" is not null) or ("metric_type" in ('weight', 'heart_rate', 'temperature', 'custom') and "numeric_value" is not null and "systolic_value" is null and "diastolic_value" is null)),
      constraint "health_metric_records_template_shape_check" check (("metric_type" = 'custom' and "template_id" is not null) or ("metric_type" in ('weight', 'blood_pressure', 'heart_rate', 'temperature') and "template_id" is null))
    );`);
    this.addSql('create index "idx_health_metric_records_user_type_measured_at" on "health_metric_records" ("user_id", "metric_type", "measured_at" desc);');
    this.addSql('create index "idx_health_metric_records_template_measured_at" on "health_metric_records" ("template_id", "measured_at" desc);');

    this.addSql(`create table "health_analyses" (
      "id" integer generated by default as identity primary key,
      "user_id" integer not null,
      "input_snapshot" jsonb not null,
      "context_snapshot" jsonb not null,
      "result_snapshot" jsonb not null,
      "schema_version" varchar(20) null,
      "created_at" timestamptz not null,
      constraint "health_analyses_user_id_foreign" foreign key ("user_id") references "users" ("id")
    );`);
    this.addSql('create index "idx_health_analyses_user_id_created_at" on "health_analyses" ("user_id", "created_at" desc);');

    this.addSql(`create table "health_knowledge" (
      "id" integer generated by default as identity primary key,
      "title" varchar(200) not null,
      "summary" text null,
      "content" text not null,
      "category" varchar(50) not null,
      "tags" text[] not null,
      "source_name" varchar(200) not null,
      "source_url" text null,
      "is_published" boolean not null,
      "created_at" timestamptz not null,
      "updated_at" timestamptz not null
    );`);
    this.addSql('create index "idx_health_knowledge_category_published" on "health_knowledge" ("category", "is_published");');
  }

  override down(): void {
    throw new Error('该迁移为保留数据迁移；禁止自动回滚或删除新健康表。');
  }
}
