import { request } from '../../../api/request'
import type { ApiEnvelope } from '../../../api/types'
import type { CreateAssessmentInput, CreateMeasurementInput, HealthAssessment, HealthAssessmentResult, HealthConsent, HealthKnowledge, HealthMeasurement, HealthProfile, HealthTriage, PageResult, TriageLevel } from '../types/health'

function record(value: unknown, field = '响应'): Record<string, unknown> { if (typeof value !== 'object' || value === null) throw new Error(`服务器返回的${field}格式无效。`); return value as Record<string, unknown> }
function string(value: unknown, field: string, nullable = false): string | null { if (nullable && value === null) return null; if (typeof value !== 'string') throw new Error(`服务器返回的${field}格式无效。`); return value }
function number(value: unknown, field: string): number { if (typeof value !== 'number' || !Number.isFinite(value)) throw new Error(`服务器返回的${field}格式无效。`); return value }
function strings(value: unknown, field: string): string[] { if (!Array.isArray(value) || value.some(item => typeof item !== 'string')) throw new Error(`服务器返回的${field}格式无效。`); return value }
function triage(value: unknown): HealthTriage { const data = record(value, '分诊'); const level = data.level; if (level !== 'emergency' && level !== 'urgent' && level !== 'routine' && level !== 'self_care' && level !== 'insufficient') throw new Error('服务器返回的分诊等级格式无效。'); return { level, reasonCodes: strings(data.reasonCodes, '分诊原因'), message: string(data.message, '分诊说明')! } }
function profile(value: unknown): HealthProfile { const data = record(value, '健康档案'); return { medicalHistory: string(data.medicalHistory, '既往健康情况', true), allergies: string(data.allergies, '过敏信息', true), specialPopulation: string(data.specialPopulation, '特殊人群信息', true), updatedAt: string(data.updatedAt, '更新时间', true) } }
function consent(value: unknown): HealthConsent { const data = record(value, '健康同意'); const scopes = strings(data.scopes, '同意范围'); if (scopes.some(scope => !['profile', 'measurement', 'assessment', 'ai_processing'].includes(scope))) throw new Error('服务器返回的同意范围格式无效。'); return { id: string(data.id, '同意编号')!, noticeVersion: string(data.noticeVersion, '告知版本')!, scopes: scopes as HealthConsent['scopes'], grantedAt: string(data.grantedAt, '同意时间')! } }
function measurement(value: unknown): HealthMeasurement { const data = record(value, '健康测量'); const type = data.type; const source = data.source; if (!['blood_pressure', 'body_temperature', 'heart_rate', 'body_weight', 'body_height'].includes(String(type)) || !['self_reported', 'manual_device', 'connected_device'].includes(String(source))) throw new Error('服务器返回的测量类型格式无效。'); const rawValues = record(data.values, '测量数值'); const values: Record<string, string | number> = {}; for (const [key, item] of Object.entries(rawValues)) { if (typeof item !== 'string' && (typeof item !== 'number' || !Number.isFinite(item))) throw new Error('服务器返回的测量数值格式无效。'); values[key] = item } return { id: string(data.id, '测量编号')!, type: type as HealthMeasurement['type'], source: source as HealthMeasurement['source'], measuredAt: string(data.measuredAt, '测量时间')!, values, createdAt: string(data.createdAt, '创建时间')! } }
function result(value: unknown): HealthAssessmentResult { const data = record(value, '评估结果'); const references = data.knowledgeReferences; if (!Array.isArray(references)) throw new Error('服务器返回的知识引用格式无效。'); return { schemaVersion: string(data.schemaVersion, '结果版本')!, triage: triage(data.triage), summary: string(data.summary, '结果摘要')!, factors: strings(data.factors, '影响因素'), nextActions: strings(data.nextActions, '后续行动'), selfCare: strings(data.selfCare, '自我照护'), warningSignals: strings(data.warningSignals, '警示信号'), knowledgeReferences: references.map(item => { const reference = record(item, '知识引用'); return { knowledgeId: number(reference.knowledgeId, '知识编号'), version: number(reference.version, '知识版本'), title: string(reference.title, '知识标题')! } }), limitations: strings(data.limitations, '结果局限'), aiGenerated: data.aiGenerated === true, generatedAt: string(data.generatedAt, '生成时间')! } }
function assessment(value: unknown): HealthAssessment { const data = record(value, '健康评估'); if (data.status !== 'succeeded' && data.status !== 'failed' && data.status !== 'processing') throw new Error('服务器返回的评估状态格式无效。'); return { id: string(data.id, '评估编号')!, status: data.status, triage: triage(data.triage), result: result(data.result), aiGenerated: data.aiGenerated === true, ruleVersion: string(data.ruleVersion, '规则版本')!, createdAt: string(data.createdAt, '创建时间')!, completedAt: string(data.completedAt, '完成时间', true) } }
function page<T>(value: unknown, parse: (item: unknown) => T): PageResult<T> { const data = record(value, '分页结果'); if (!Array.isArray(data.list)) throw new Error('服务器返回的列表格式无效。'); return { list: data.list.map(parse), total: number(data.total, '总数'), page: number(data.page, '页码'), pageSize: number(data.pageSize, '每页数量') } }
async function unwrap<T>(call: Promise<{ data: ApiEnvelope<unknown> }>, parse: (value: unknown) => T): Promise<T> { const response = await call; return parse(response.data.data) }

export const healthApi = {
  currentConsent: (): Promise<HealthConsent | null> => unwrap(request.get<ApiEnvelope<unknown>>('/api/v2/health/consents/current'), value => value === null ? null : consent(value)),
  grantConsent: (scopes: HealthConsent['scopes']): Promise<HealthConsent> => unwrap(request.post<ApiEnvelope<unknown>>('/api/v2/health/consents', { noticeVersion: '1.0', scopes }), consent),
  revokeConsent: async (): Promise<void> => { await request.delete('/api/v2/health/consents/current') },
  getProfile: (): Promise<HealthProfile> => unwrap(request.get<ApiEnvelope<unknown>>('/api/v2/health/profile'), profile),
  updateProfile: (input: Partial<Pick<HealthProfile, 'medicalHistory' | 'allergies' | 'specialPopulation'>>): Promise<HealthProfile> => unwrap(request.patch<ApiEnvelope<unknown>>('/api/v2/health/profile', input), profile),
  measurements: (): Promise<PageResult<HealthMeasurement>> => unwrap(request.get<ApiEnvelope<unknown>>('/api/v2/health/measurements'), value => page(value, measurement)),
  createMeasurement: (input: CreateMeasurementInput): Promise<HealthMeasurement> => unwrap(request.post<ApiEnvelope<unknown>>('/api/v2/health/measurements', input), measurement),
  deleteMeasurement: async (id: string): Promise<void> => { await request.delete(`/api/v2/health/measurements/${encodeURIComponent(id)}`) },
  assessments: (): Promise<PageResult<HealthAssessment>> => unwrap(request.get<ApiEnvelope<unknown>>('/api/v2/health/assessments'), value => page(value, assessment)),
  createAssessment: (input: CreateAssessmentInput): Promise<HealthAssessment> => unwrap(request.post<ApiEnvelope<unknown>>('/api/v2/health/assessments', input, { timeout: 300_000 }), assessment),
  deleteAssessment: async (id: string): Promise<void> => { await request.delete(`/api/v2/health/assessments/${encodeURIComponent(id)}`) },
  knowledge: (keyword = ''): Promise<HealthKnowledge[]> => unwrap(request.get<ApiEnvelope<unknown>>('/api/v2/health/knowledge', { params: keyword ? { keyword } : undefined }), value => { if (!Array.isArray(value)) throw new Error('服务器返回的健康知识格式无效。'); return value.map(item => { const data = record(item, '健康知识'); return { knowledgeId: number(data.knowledgeId, '知识编号'), version: number(data.version, '知识版本'), title: string(data.title, '知识标题')!, excerpt: string(data.excerpt, '知识摘要')!, sourceName: string(data.sourceName, '知识来源')!, sourceUrl: string(data.sourceUrl, '知识链接')!, reviewedAt: string(data.reviewedAt, '审核时间')!, score: number(data.score, '相关度') } }) }),
}

export function isFailSafeTriage(level: TriageLevel): boolean { return level === 'insufficient' }
