<script setup lang="ts">
import { onMounted, reactive, shallowRef } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getAdminFacingError } from '../../../app/auth'
import { agricultureAdminApi } from '../api/agriculture'
import type { Crop, CropStatus } from '../types/agriculture'
const crops = shallowRef<Crop[]>([]); const loading = shallowRef(false); const dialogVisible = shallowRef(false); const editing = shallowRef<Crop | null>(null)
const form = reactive({ code: '', name: '', scientificName: '', status: 'active' as CropStatus, alias: '' })
async function load(): Promise<void> { loading.value = true; try { crops.value = await agricultureAdminApi.crops() } catch (error) { ElMessage.error(getAdminFacingError(error)) } finally { loading.value = false } }
function openCreate(): void { editing.value = null; Object.assign(form, { code: '', name: '', scientificName: '', status: 'active', alias: '' }); dialogVisible.value = true }
function openEdit(crop: Crop): void { editing.value = crop; Object.assign(form, { code: crop.code, name: crop.name, scientificName: crop.scientificName ?? '', status: crop.status, alias: '' }); dialogVisible.value = true }
async function save(): Promise<void> { if (!form.name.trim() || (!editing.value && !form.code.trim())) return; try { if (editing.value) await agricultureAdminApi.updateCrop(editing.value.id, { name: form.name.trim(), scientificName: form.scientificName.trim() || null, status: form.status }); else await agricultureAdminApi.createCrop({ code: form.code.trim(), name: form.name.trim(), scientificName: form.scientificName.trim() || null }); ElMessage.success('作物目录已保存'); dialogVisible.value = false; await load() } catch (error) { ElMessage.error(getAdminFacingError(error)) } }
async function addAlias(): Promise<void> { if (!editing.value || !form.alias.trim()) return; try { await agricultureAdminApi.addAlias(editing.value.id, form.alias.trim()); form.alias = ''; await load(); ElMessage.success('别名已添加') } catch (error) { ElMessage.error(getAdminFacingError(error)) } }
async function removeAlias(crop: Crop, aliasId: number): Promise<void> { try { await ElMessageBox.confirm('确定删除该别名吗？', '删除别名', { type: 'warning' }); await agricultureAdminApi.removeAlias(crop.id, aliasId); await load(); ElMessage.success('别名已删除') } catch (error) { if (error !== 'cancel') ElMessage.error(getAdminFacingError(error)) } }
onMounted(load)
</script>
<template><section class="catalog"><div class="toolbar"><div><h2>作物目录</h2><p>维护用户端可选作物及其检索别名。</p></div><el-button type="primary" @click="openCreate">新建作物</el-button></div><el-table v-loading="loading" :data="crops" stripe><el-table-column prop="name" label="作物名称" min-width="150" /><el-table-column prop="code" label="编码" min-width="120" /><el-table-column prop="scientificName" label="学名" min-width="180" /><el-table-column label="别名" min-width="200"><template #default="{ row }"><el-tag v-for="alias in row.aliases" :key="alias.id" closable class="alias" @close="removeAlias(row, alias.id)">{{ alias.alias }}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="row.status === 'active' ? 'success' : 'info'">{{ row.status === 'active' ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="100"><template #default="{ row }"><el-button link type="primary" @click="openEdit(row)">编辑</el-button></template></el-table-column></el-table><el-dialog v-model="dialogVisible" :title="editing ? '编辑作物' : '新建作物'" width="500"><el-form label-width="88px"><el-form-item label="作物编码" required><el-input v-model="form.code" :disabled="Boolean(editing)" maxlength="64" /></el-form-item><el-form-item label="作物名称" required><el-input v-model="form.name" maxlength="100" /></el-form-item><el-form-item label="学名"><el-input v-model="form.scientificName" maxlength="255" /></el-form-item><el-form-item v-if="editing" label="状态"><el-radio-group v-model="form.status"><el-radio value="active">启用</el-radio><el-radio value="inactive">停用</el-radio></el-radio-group></el-form-item><el-form-item v-if="editing" label="添加别名"><el-input v-model="form.alias" maxlength="100" @keyup.enter="addAlias"><template #append><el-button @click="addAlias">添加</el-button></template></el-input></el-form-item></el-form><template #footer><el-button @click="dialogVisible = false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></section></template>
<style scoped>.catalog { padding: 24px; }.toolbar { display: flex; align-items: center; justify-content: space-between; margin-bottom: 20px; }.toolbar h2 { margin: 0 0 6px; font-size: 20px; }.toolbar p { color: var(--color-text-secondary); font-size: 14px; }.alias { margin: 2px; }</style>
